sudo: required
dist: trusty
language: node_js
notifications:
  email: false
branches:
  only:
    - master
    - /^greenkeeper-.*$/
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "7"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - sudo apt-get install python2.7 git-all pkg-config libncurses5-dev libssl-dev libnss3-dev libexpat-dev -y
  - npm config set python python2
  - sudo apt-get update -qq
  - npm install wrtc@0.0.60
  - npm install uws
  - npm install -g codeclimate-test-reporter
script:
  - npm run test:travis
after_success:
  - codeclimate-test-reporter < ./coverage/lcov.info
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
